#!/usr/bin/env node

import { Command } from 'commander';
const parser = new Command();
import scrape from './commands/scrape.js';

parser.
	name('ldsh')
	.description('Tools for extracting your ward/stake directory into a usable dataset')
	.version('0.0.1')

parser.command('scrape')
	.description('Exports the directory available to the user')
	.arguments('unitsFile', '' +
		'Path to a text file containing the unit numbers you would like info for. ' +
		'One unit number on each line.')
	.arguments('headersFile', '' +
		'Path to a file containing request headers. ' +
		'You can get these request headers from the chrome network tab. ' +
		'Headers file should at a minimum contain \'Cookie: <cookies>\' as its own line. ' +
		'This is to authenticate your requests to the church directory APIs.' +
		'If you don\'t know how to get these request headers and don\'t know what any of this means...' +
		'don\'t use this tool.')
	.action(scrape)



parser.parse()
